spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_service?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    hikari:
      read-only: false

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
      show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        connection:
          read_only: false
    open-in-view: false


server:
  port: 8085
  servlet:
    context-path: /api/v1/user_service

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://192.168.10.18:8761/eureka
  instance:
    prefer-ip-address: true

logging:
  file:
    name: ./logs/user-service.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com.billit.user_service: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
  token-validity-in-milliseconds: 3600000